### ISSUE TITLE
Should we move ahead with sqlite or postgres

### ISSUE THREAD

**Issue by n1rjal** [n1rjal/djate#1]
👀 For Postgres
🚀 For Sqlite

**Comment by chidoziemanagwu** [comment]
Production is Postgres
Development is SQLite

**Comment by n1rjal** [comment]
You can create a PR for the following 

Add an environment variable called DB_USED=postgres or sqlite
and depending upon the environment variable called, the template will use either one of them

Also don't forget to add other required environment variables like postgres username, postgres password, host, port, etc
