### ISSUE TITLE
SECRET_KEY is exposed 

### ISSUE THREAD

**Issue by kavyachouhan** [n1rjal/djate#11]
To hide the SECRET_KEY and other sensitive information in the Django project, I can implement environment variables.

![image](https://github.com/user-attachments/assets/b9d718e7-4a15-4437-8bc4-9bbcf0d4666c)

**Comment by n1rjal** [comment]
You can change it to use env file. Thanks @kavyachouhan

**Comment by kavyachouhan** [comment]
@n1rjal Assign it to me and please add hacktoberfest label.
