### ISSUE TITLE
Is the Project using Poetry as the package manager?

### ISSUE THREAD

**Issue by Minty-cyber** [n1rjal/djate#23]
A quick question @n1rjal , is the project using Poetry as the package manager or just the traditional pip, cos I see a `.toml ` file but I do not see a `poetry.lock` file. Would you like to use poetry as the package manager and maintain the `.toml` file? If so, should I do that fix?

**Comment by n1rjal** [comment]
sorry, I am planning to move away from both of them and switch to uv. If you want to implement it, feel free to do so

**Comment by Minty-cyber** [comment]
Oh yeah sure i can implement uv instead. I will do that then
