### ISSUE TITLE
Set up a logging solution

### ISSUE THREAD

**Issue by n1rjal** [n1rjal/djate#3]
I am looking for someone to setup a logging solution. You can use any logging package (or use any django package) of your choice. 

The logging package should have the following. You can just submit partial solution and wait for others to come around
[ ] FiIe system logging
[ ] Aws Cloudwatch logs

**Comment by Vineet8800** [comment]
@n1rjal I would like to work on this too. Assign it to me and please add hacktoberfest label.

**Comment by n1rjal** [comment]
Go ahead @Vineet8800
