### ISSUE TITLE
Intregate Sentry

### ISSUE THREAD

**Issue by n1rjal** [n1rjal/djate#4]
Sentry is a monitoring platform used to track and diagnose application errors in real-time. It helps developers identify, understand, and resolve issues that occur in their applications. Sentry supports a variety of programming languages, frameworks, and platforms, allowing it to be integrated into web, mobile, and desktop apps.

You can use sentry's documentation on how to get started with Django and implement it. Make sure you use the environment file and update its entry with an example of env.example file

**Comment by Vineet8800** [comment]
@n1rjal I would like to work on this. Assign it to me and please add hacktoberfest label.

**Comment by n1rjal** [comment]
Done @Vineet8800. Good luck ahead.
